# The Citation between DOCDB families table (TLS228_DOCDB_FAM_CITN)

Welcome to the **Citation between DOCDB families table**, coded as TLS228_DOCDB_FAM_CITN. This table contains one entry for each pair of DOCDB simple families, where one member of a family cites at least one member of another family. That means if multiple publications of one family cite one or multiple publication(s) / application(s) of another family, then this is counted as one citation between these two families.

In this table, both cited publications (typical case) and cited applications (also possible) are considered.

In [1]:
from epo.tipdata.patstat import PatstatClient

# Initialize the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

# Importing the as models
from epo.tipdata.patstat.database.models import TLS228_DOCDB_FAM_CITN

## DOCDB_FAMILY_ID

This attribute provides a link to table TLS201 and it is the identifier of a DOCDB simple family.

In [2]:
# Import table TLS201
from epo.tipdata.patstat.database.models import TLS201_APPLN

show_join = db.query(
    TLS201_APPLN.docdb_family_id,
    TLS228_DOCDB_FAM_CITN.cited_docdb_family_id
).join(
    TLS201_APPLN, TLS228_DOCDB_FAM_CITN.docdb_family_id == TLS201_APPLN.docdb_family_id
).limit(1000)

show_join_df = patstat.df(show_join)
show_join_df

     docdb_family_id  cited_docdb_family_id
0           19507204               11792450
1           19507204               11792450
2           19507204               11792450
3           19507204               11792450
4           26346567               17087027
..               ...                    ...
995         53801116               24563484
996         56849669               56552882
997         56849669               56552882
998         56849669               56552882
999         37648738               24639426

[1000 rows x 2 columns]

## CITED_DOCDB_FAMILY_ID

ID of the cited DOCDB simple family. Uniquely identifies the cited family.

With this attribute, we can for example retrieve the five most cited DOCDB family among the ones having applications filed at the EPO.

In [3]:
from sqlalchemy import func

most_cited_fams = db.query(
    TLS228_DOCDB_FAM_CITN.cited_docdb_family_id,
    func.count(TLS201_APPLN.docdb_family_id).label('Total citations')
).join(
    TLS228_DOCDB_FAM_CITN, TLS201_APPLN.docdb_family_id == TLS228_DOCDB_FAM_CITN.docdb_family_id
).filter(
    TLS201_APPLN.appln_auth == 'EP'
).group_by(
    TLS228_DOCDB_FAM_CITN.cited_docdb_family_id
).order_by(
    func.count(TLS201_APPLN.docdb_family_id).desc()
).limit(5)

most_cited_fams_df = patstat.df(most_cited_fams)
most_cited_fams_df

   cited_docdb_family_id  Total citations
0               23920101             9641
1               27109640             7542
2               24543134             6411
3               27124781             5970
4               27399321             4708