# The Cooperative Patent Classification by application (TLS224_APPLN_CPC)

Welcome to the Cooperative Patent Classification by application table in PATSTAT, identified with the name TLS224_APPLN_CPC. The table contains for each application its assigned Cooperative Patent Classification (CPC symbols). All applications of the same DOCDB family have the same CPC symbols assigned.

In [1]:
from epo.tipdata.patstat import PatstatClient

# Initialize the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

# Importing the as models
from epo.tipdata.patstat.database.models import TLS224_APPLN_CPC

## APPLN_ID

Also in this case we have a link to table TLS201 via the ``appln_id`` attribute.

In [2]:
# Import table TLS201
from epo.tipdata.patstat.database.models import TLS201_APPLN

show_join = db.query(
    TLS201_APPLN.appln_id,
    TLS201_APPLN.appln_auth,
    TLS224_APPLN_CPC.cpc_class_symbol
).join(
    TLS201_APPLN, TLS224_APPLN_CPC.appln_id == TLS201_APPLN.appln_id
).limit(1000)

show_join_df = patstat.df(show_join)
show_join_df

      appln_id appln_auth cpc_class_symbol
0    339185770         US   F15B2211/31576
1    591089506         US    B60G2206/7104
2    477103837         US      H02S  40/30
3    610753098         CN      B32B  15/18
4     14682494         DE      A61P  25/00
..         ...        ...              ...
995   42433622         PL      A61K   8/25
996   57168050         CN    H04L  43/0829
997  581855947         ES   B01J2208/00849
998  341246097         DK      G01N2333/54
999  438553579         WO      G06Q  30/02

[1000 rows x 3 columns]

## CPC_CLASS_SYMBOL

Classification symbol according to the Cooperative Patent Classification. It consists of up to 19 characters (A-Z, 0-9, /, space).

In [3]:
from sqlalchemy import func

symb_appln = db.query(
    TLS224_APPLN_CPC.appln_id,
    func.count(TLS224_APPLN_CPC.cpc_class_symbol).label('Number of symbols')
).group_by(
    TLS224_APPLN_CPC.appln_id
).having(
    func.count(TLS224_APPLN_CPC.cpc_class_symbol) > 1  # Consider only applications with more than 1 class symbol
).order_by(
    func.count(TLS224_APPLN_CPC.cpc_class_symbol).desc()
).limit(1000)

symb_appln_df = patstat.df(symb_appln)
symb_appln_df

      appln_id  Number of symbols
0     41351949                333
1      8025569                333
2     53279350                333
3    323782095                333
4     40903505                333
..         ...                ...
995   48265741                144
996   48060422                144
997   15860587                144
998   37149309                144
999   53513227                144

[1000 rows x 2 columns]

In [4]:
appln_symb = db.query(
    TLS224_APPLN_CPC.cpc_class_symbol,
    func.count(TLS224_APPLN_CPC.appln_id).label('Number of symbols')
).group_by(
    TLS224_APPLN_CPC.cpc_class_symbol
).having(
    func.count(TLS224_APPLN_CPC.appln_id) > 1  # Consider only applications with more than 1 class symbol
).order_by(
    func.count(TLS224_APPLN_CPC.appln_id).desc()
)

appln_symb_df = patstat.df(appln_symb)
appln_symb_df

       cpc_class_symbol  Number of symbols
0           Y02E  60/10            1178253
1           A61P  35/00            1086963
2           A61P  43/00            1016242
3           A61P  29/00             651973
4           A61P  25/00             554627
...                 ...                ...
252368      C14B2700/00                  2
252369   G05B2219/32108                  2
252370    A63F2009/0676                  2
252371   C12N2760/12232                  2
252372   C12Y 301/01045                  2

[252373 rows x 2 columns]