# The REG130_OPPONENT table

Welcome to an in-depth exploration of the REG130_OPPONENT table, a significant component of PATSTAT Register. This table captures essential details about opponents who file opposition to patents, a process that allows third parties to contest the validity of a granted patent. The opposition procedure is a cornerstone of maintaining patent quality, ensuring that only inventions meeting the stringent requirements of the European Patent Convention (EPC) are protected.

The ``REG130_OPPONENT`` table provides a comprehensive record of opponents and their agents, including names, addresses, and countries.

The opposition process allows third parties to challenge the validity of a granted European patent. The ``REG130_OPPONENT`` table captures key information about these proceedings, including the identity of the opponent, filing details, and procedural updates.

The opposition process follows specific stages, each marked by important dates:

1. When an opposition is filed:
   - ``DATE_OPP_FILED`` (date of opposition filing): this is the official date when the opposition is submitted to the EPO. It marks the start of the legal challenge against the granted patent.
   - ``BULLETIN_YEAR`` and ``BULLETIN_NR`` (publication of opposition): the opposition is officially published in the European Patent Bulletin, allowing public awareness of the challenge. These fields record the year and European Patent Bulletin number in which the opposition appeared.
2. Tracking the status of the opposition:
   - ``OPPT_STATUS`` (opponent status): this field indicates the current stage of the opposition, such as "Admissible" or other procedural statuses.
   - ``OPPT_STATUS_DATE`` (date of status change): The date when the last update was made to the opponent's status, helping to track the progression of the case.
3. Opponent and legal representation:
   - ``OPPT_NAME`` (opponent’s name) and ``OPPT_COUNTRY`` (opponent’s country): these fields provide details about the entity or individual opposing the patent and their geographical location.
   - ``AGENT_NAME`` (representative’s name) and ``AGENT_COUNTRY`` (agent’s country): if the opponent is represented by a patent attorney or legal firm, these fields record their identity and location.
Together, these fields provide a structured view of the opposition process, from initial filing to procedural updates, allowing for a comprehensive analysis of patent disputes.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG130_OPPONENT, REG101_APPLN
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

In [2]:
q = db.query(
    REG130_OPPONENT.id,
    REG130_OPPONENT.change_date,
    REG130_OPPONENT.bulletin_year,
    REG130_OPPONENT.bulletin_nr,
    REG130_OPPONENT.is_latest,
    REG130_OPPONENT.oppt_nr,
    REG130_OPPONENT.customer_id,
    REG130_OPPONENT.oppt_name,
    REG130_OPPONENT.oppt_address_1,
    REG130_OPPONENT.oppt_address_2,
    REG130_OPPONENT.oppt_address_3,
    REG130_OPPONENT.oppt_address_4,
    REG130_OPPONENT.oppt_address_5,
    REG130_OPPONENT.oppt_country,
    REG130_OPPONENT.date_opp_filed,
    REG130_OPPONENT.oppt_status,
    REG130_OPPONENT.oppt_status_date,
    REG130_OPPONENT.agent_name,
    REG130_OPPONENT.agent_address_1,
    REG130_OPPONENT.agent_address_2,
    REG130_OPPONENT.agent_address_3,
    REG130_OPPONENT.agent_address_4,
    REG130_OPPONENT.agent_address_5,
    REG130_OPPONENT.agent_country
)

res = patstat.df(q)
res

,id,change_date,bulletin_year,bulletin_nr,is_latest,oppt_nr,customer_id,oppt_name,oppt_address_1,oppt_address_2,...,date_opp_filed,oppt_status,oppt_status_date,agent_name,agent_address_1,agent_address_2,agent_address_3,agent_address_4,agent_address_5,agent_country
0,79300770,1982-06-04,1982,31,N,1,0100707322,AMP Incorporated,,,...,1982-05-24,,9999-12-31,"Wayte, Dennis Travers",,,,,,GB
1,80102304,1984-06-01,1984,31,N,1,0100701020,"Degussa AG, Frankfurt - Zweigniederlassung Wol...",,,...,1984-05-23,ADMISSIBLE,1984-06-29,,,,,,,
2,78400114,1982-02-04,1982,14,N,1,0100715070,Muiden Chemie B.V.,,,...,1982-01-13,,9999-12-31,"Urbanus, Henricus Maria, Ir., et al",,,,,,NL
3,79302654,1984-03-12,1984,20,Y,1,0100716031,Phoenix Aktiengesellschaft,,,...,1984-03-01,ADMISSIBLE,1984-05-02,,,,,,,
4,80103046,1984-09-27,1984,48,N,1,0100709849,Dr. Christian Brunnengräber GmbH,,,...,1984-09-25,,9999-12-31,"Möllering, Karl Friedrich",,,,,,DE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378683,21886838,2025-02-14,2025,12,N,1,0101895605,"Nippon Shokubai Co., Ltd.",,,...,2025-02-07,,9999-12-31,Herzog IP Patentanwalts GmbH,,,,,,DE
378684,19700228,2025-07-18,2025,34,Y,1,0102098974,InPera IP Fikri Mülkiyet Danismanlik ve Egitim...,,,...,2025-07-11,ADMISSIBLE,2025-07-15,"Hamamcioglu, Volkan",,,,,,TR
378685,18703405,2025-04-11,2025,20,Y,1,0101996940,"Molzen, Lennart",,,...,2024-03-07,ADMISSIBLE,2024-03-08,"Straus, Alexander",,,,,,DE
378686,18716528,2025-01-17,2025,8,N,1,0101035557,Henkel AG & Co. KGaA,,,...,2025-01-16,,9999-12-31,,,,,,,
378687,23152997,2025-07-04,2025,32,N,1,0101534201,ArcelorMittal,,,...,2025-06-20,ADMISSIBLE,2025-06-23,Lavoix,,,,,,FR

## Key fields in the REG130_OPPONENT table

### ID (primary key) 
The ID field serves as a technical identifier that uniquely connects patent applications across various tables.

### CHANGE_DATE (primary key) 
The ``CHANGE_DATE`` captures the date when the opponent-related data was last updated in the database. This is crucial for monitoring the evolution of opposition records and ensuring that the most accurate and recent data is available.

### BULLETIN_YEAR (primary Key)

In the PATSTAT database, the ``BULLETIN_YEAR`` field captures the year when an action or event related to a patent application was published in the European Patent Bulletin. This field plays a critical role in tracking the timeline of patent events, ensuring chronological accuracy in analyses.

The ``BULLETIN_YEAR`` is a 4-digit numeric field (formatted as YYYY), with a default value of 0 to indicate cases where no European Patent Bulletin publication is known. For entries where publication in the European Patent Bulletin is confirmed, ``BULLETIN_YEAR`` reflects the corresponding year of publication. It is used in conjunction with ``BULLETIN_NR``, which specifies the European Patent Bulletin issue number.

### BULLETIN_NR (primary key)

The ``BULLETIN_NR`` attribute represents the issue number of the European Patent Bulletin in which a specific action has been published. This number indicates the calendar week during which the European Patent Bulletin was released. It serves as a reference for identifying the exact edition of the European Patent Bulletin where actions such as patent grants, publications, or other significant events are announced.

If the action was not published in the European Patent Bulletin or if the information is unknown, the default value of 0 is used for the ``BULLETIN_NR``, which corresponds to the absence of a known European Patent Bulletin number. This value is only used when the associated ``BULLETIN_YEAR`` is also set to 0.

### IS_LATEST (indicates latest records)
The ``IS_LATEST`` attribute acts as a flag to identify the most recent and active set of opponents for a given patent application. A value of "Y" indicates the current records, while "N" marks older, historical entries.

In [3]:
q = db.query(
    REG130_OPPONENT.is_latest
).distinct()

res = patstat.df(q)
res

  is_latest
0         N
1         Y

### OPPT_NR (opponent sequence number) (primary key)
The ``OPPT_NR`` is a unique sequence number assigned to each opponent involved in opposing a specific patent. This number helps distinguish multiple opponents within the same application. Typically starting from 1, it ensures proper identification of individual opponents and their associated details, even when several parties are engaged in the same opposition procedure.

### CUSTOMER_ID (customer identifier)
The ``CUSTOMER_ID represents`` a unique identifier assigned to an opponent. This ID links opponents to the EPO address book, allowing consistent identification of the legal or natural person across various roles, such as opponent, applicant, or representative. It provides a systematic way to track and manage opponent records.

### OPPT_NAME (opponent name)
The ``OPPT_NAME`` attribute contains the name of the opponent filing the opposition. This field can hold up to 255 characters, ensuring accurate representation of individual or organizational names in the database.

### OPPT_ADDRESS_1 to OPPT_ADDRESS_5 (opponent address lines)
The ``OPPT_ADDRESS`` attributes capture the opponent’s full address, spread across up to five lines. This detailed breakdown allows for comprehensive address storage, accommodating various address formats used globally.

### OPPT_COUNTRY (opponent country)
The ``OPPT_COUNTRY`` field specifies the country of the opponent. It provides geographical context to opposition filings, enabling analysis of opposition activity by region.

In [4]:
q = db.query(
    REG130_OPPONENT.oppt_name,
    func.count(REG130_OPPONENT.id).label("num_oppositions")
).group_by(REG130_OPPONENT.oppt_name).order_by(func.count(REG130_OPPONENT.id).desc())

res = patstat.df(q)
res

                              oppt_name  num_oppositions
0            Siemens Aktiengesellschaft             3753
1          The Procter & Gamble Company             3491
2                  Henkel AG & Co. KGaA             3446
3                            Siemens AG             2600
4               BASF Aktiengesellschaft             2475
...                                 ...              ...
32376               O-synce Europe GmbH                1
32377  Royal Vaassen Flexible Packaging                1
32378               CEMBRIT HOLDING A/S                1
32379           Quorum Technologies Ltd                1
32380                   Afag Holding AG                1

[32381 rows x 2 columns]

This query is counting the number of opposition records for each opponent (identified by their name) in the ``REG130_OPPONENT`` table. It groups the results by the opponent's name , counting how many times each opponent appears in the database, and orders the results in descending order based on the number of oppositions. The result provides an overview of which opponents have filed the most opposition requests against patents.

### Date opp filed (date opposition filed)
The ``DATE_OPP_FILED`` records the date when the opposition was officially filed. This timestamp is critical for understanding the timeline of opposition activities and compliance with procedural deadlines.

In [5]:
q = db.query(
    REG130_OPPONENT.oppt_name,
    REG130_OPPONENT.oppt_country,
    REG130_OPPONENT.date_opp_filed
).filter(REG130_OPPONENT.oppt_country == "DE").order_by(REG130_OPPONENT.date_opp_filed)

res = patstat.df(q)
res

                      oppt_name oppt_country date_opp_filed
0             Akzo Patente GmbH           DE     1980-09-29
1       Hüls Aktiengesellschaft           DE     1980-11-13
2       Hüls Aktiengesellschaft           DE     1980-11-13
3       Hüls Aktiengesellschaft           DE     1980-11-13
4       Hüls Aktiengesellschaft           DE     1980-11-13
...                         ...          ...            ...
183016         Analytik Jena AG           DE     9999-12-31
183017               Braun GmbH           DE     9999-12-31
183018     BOXLER GMBH & CO. KG           DE     9999-12-31
183019         Analytik Jena AG           DE     9999-12-31
183020               Degussa AG           DE     9999-12-31

[183021 rows x 3 columns]

### OPPT_STATUS (opponent status)
The ``OPPT_STATUS indicates`` the current status of the opponent in the opposition procedure. It reflects whether the opponent remains active, has withdrawn, or is otherwise no longer contesting the patent.

In [6]:
q = db.query(
    REG130_OPPONENT.oppt_status
).filter(
    REG130_OPPONENT.oppt_status != ""
).distinct()

res = patstat.df(q)
res

                     oppt_status
0                      WITHDRAWN
1        INTERVENTION ADMISSIBLE
2         INTERVENTION WITHDRAWN
3      INTERVENTION INADMISSIBLE
4  INTERVENTION DEEMED NOT FILED
5                     ADMISSIBLE
6                   INTERVENTION
7  DEEMED NOT TO HAVE BEEN FILED
8                   INADMISSIBLE

### OPPT_STATUS_DATE (opponent status date)
The ``OPPT_STATUS_DATE`` provides the date when the opponent’s status last changed. This is useful for tracking updates to the involvement of an opponent over time.

### AGENT_NAME (agent name)
The ``AGENT_NAME`` field records the name of the representative or agent acting on behalf of the opponent. This ensures that the legal representation of the opponent is clearly documented.

### AGENT_ADDRESS_1 to AGENT_ADDRESS_5 (agent address lines)
The ``AGENT_ADDRESS`` attributes store the complete address of the agent representing the opponent. Similar to the opponent address, this information is spread across five lines for detailed recording.

### AGENT_COUNTRY (agent country)
The ``AGENT_COUNTRY`` specifies the country where the agent operates. This attribute helps provide geographical insights into the legal representation involved in opposition cases.