# The REG125_APPEAL table

Welcome to a comprehensive exploration of one of the tables in the PATSTAT database: the ``REG125_APPEAL`` table. This table tracks the appeals filed under the **European Patent Convention (EPC), providing insights into the legal process and the progression of patent applications through the appeal stages.

The ``REG125_APPEAL`` table contains detailed information regarding the appeals filed under the EPC particularly for appeals related to patent applications. Appeals are part of the legal process outlined under Articles A.108 to A.111 of the EPC, and an individual application may have multiple appeals associated with it.

This data is essential for understanding the appeals process in the European patent system, including the progression and outcomes of appeals, and it is linked to the ``REG101_APPLN`` table by the ID field, ensuring a connection to the relevant patent applications.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG125_APPEAL, REG101_APPLN
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

In [2]:
q = db.query(
    REG125_APPEAL.id,
    REG125_APPEAL.appeal_date,
    REG125_APPEAL.appeal_nr,
    REG125_APPEAL.phase,
    REG125_APPEAL.date_state_grounds_filed,
    REG125_APPEAL.date_interloc_revision,
    REG125_APPEAL.result,
    REG125_APPEAL.result_date,
    REG101_APPLN.appln_nr,
    REG101_APPLN.appln_filing_date
).join(
    REG101_APPLN, REG125_APPEAL.id == REG101_APPLN.id  
)

res = patstat.df(q)
res

,id,appeal_date,appeal_nr,phase,date_state_grounds_filed,date_interloc_revision,result,result_date,appln_nr,appln_filing_date
0,13789795,2020-08-26,T1949/20-3207,examination,2020-08-26,2020-09-17,OTHER KIND OF DISPOSAL,2021-05-05,13789795,2013-11-12
1,92120123,1996-07-25,J0024/96-3101,examination,1996-08-01,9999-12-31,ALLOWANCE OF APPEAL,2001-04-27,92120123,1992-11-25
2,8732503,2018-03-01,T0162/19-3501,examination,9999-12-31,9999-12-31,APPEAL OF APPLICANT DEEMED NOT TO BE FILED,2019-07-19,08732503,2008-03-19
3,90901255,1992-08-17,J0046/92-3101,examination,1992-10-15,9999-12-31,APPEAL DEEMED NOT TO HAVE BEEN FILED,1995-02-03,90901255,1989-11-25
4,3781836,2012-07-30,J0017/12-3101,examination,2012-07-30,9999-12-31,ALLOWANCE OF APPEAL,2013-11-13,03781836,2003-11-10
...,...,...,...,...,...,...,...,...,...,...
78695,3764643,2009-12-15,T0678/10-3501,examination,9999-12-31,9999-12-31,WITHDRAWAL OF APPLICATION,2010-04-20,03764643,2003-07-15
78696,8776538,2017-09-25,T2798/17-3306,examination,2017-11-30,9999-12-31,WITHDRAWAL OF APPLICATION,2021-02-11,08776538,2008-06-26
78697,99946789,2005-11-24,T0310/06-3308,examination,2006-01-26,9999-12-31,WITHDRAWAL OF APPLICATION,2006-10-16,99946789,1999-09-09
78698,85303119,1990-08-07,T0922/90-3301,examination,1990-12-10,9999-12-31,WITHDRAWAL OF APPLICATION,1992-08-10,85303119,1985-05-02
78699,85100466,1989-04-11,T0592/89-3303,examination,1989-06-21,9999-12-31,WITHDRAWAL OF APPLICATION,1990-01-05,85100466,1985-01-17

## Key Fields in ``REG125_APPEAL`` table

### ID (primary key)

This is the unique identifier for each entry in the `REG125_APPEAL` table. It serves as the primary key when linking the appeal data with other tables, such as `REG101_APPLN`.

### APPEAL_DATE (primary key)

This attribute indicates the exact date when the appeal was officially filed. It marks the beginning of the appeal process and is crucial for understanding the timeline of the appeal within the patent's legal journey.

### APPEAL_NR (primary key)

The unique appeal number allocated to the specific appeal case. This number is used to distinguish different appeals filed under the same application or patent family, providing a way to track each appeal individually.

In [3]:
q = db.query(
    REG125_APPEAL.id,
    REG125_APPEAL.appeal_date,
    REG125_APPEAL.appeal_nr,
    REG101_APPLN.appln_nr,
    REG125_APPEAL.phase,
    REG125_APPEAL.date_state_grounds_filed,
    REG125_APPEAL.date_interloc_revision,
    REG125_APPEAL.result,
    REG125_APPEAL.result_date
).join(
    REG101_APPLN, REG125_APPEAL.id == REG101_APPLN.id  
).order_by(
    REG101_APPLN.appln_nr  
)

res = patstat.df(q)
res

,id,appeal_date,appeal_nr,appln_nr,phase,date_state_grounds_filed,date_interloc_revision,result,result_date
0,100011,2011-06-14,T1290/11-3403,00100011,opposition,2011-08-13,9999-12-31,WITHDRAWAL OF APPEAL OF THE PATENT PROPRIETOR,2016-09-09
1,100018,2010-07-29,T1643/10-3506,00100018,opposition,2010-11-12,9999-12-31,APPEAL OF PROPRIETOR REJECTED,2014-11-26
2,100018,2010-08-20,T1643/10-3506,00100018,opposition,2010-11-24,9999-12-31,APPEAL OF PROPRIETOR REJECTED,2014-11-26
3,100018,2010-07-27,T1643/10-3506,00100018,opposition,2010-11-19,9999-12-31,APPEAL OF PROPRIETOR REJECTED,2014-11-26
4,100023,2009-12-23,T2454/09-3207,00100023,opposition,2010-03-01,9999-12-31,MAINTENANCE IN UNAMENDED FORM,2013-07-11
...,...,...,...,...,...,...,...,...,...
78695,99973881,2007-02-19,,99973881,examination,2007-04-24,2007-07-16,,9999-12-31
78696,99973969,2008-04-30,T0876/08-3503,99973969,opposition,2008-07-10,9999-12-31,APPEAL OF PROPRIETOR REJECTED,2010-07-29
78697,99974141,2010-03-29,T1333/10-3505,99974141,examination,2010-05-28,9999-12-31,APPLICATION DEEMED TO BE WITHDRAWN,2012-08-24
78698,99974176,2007-08-22,T1385/07-3303,99974176,opposition,2007-10-22,9999-12-31,APPEAL OF OPPONENT REJECTED,2009-10-21
78699,99974203,2015-01-21,T0193/15-3503,99974203,opposition,2015-03-18,9999-12-31,APPEAL OF PROPRIETOR REJECTED,2018-10-25

### Phase

The phase of the patent procedure in which the appeal was filed. This can include phases such as examination, opposition, revocation, or limitation. Understanding the phase helps in contextualising the appeal in relation to the patent’s progression through the legal process.

In [4]:
q = db.query(
    REG125_APPEAL.phase
).distinct()

res = patstat.df(q)
res

         phase
0   opposition
1  examination
2   limitation

### DATE_STATE_GROUNDS_FILED (primary key)

The date when the statement of grounds for the appeal was filed. This is a key date that marks the submission of the formal argumentation or reasons why the appellant is seeking a revision of the decision, providing insights into the strategy behind the appeal.

### DATE_INTERLOC_REVISION (primary key)

The date on which an interlocutory revision occurred during the appeal process. An interlocutory revision is typically a decision taken by the EPO before a final decision is made, allowing some modifications or corrections to be made before the case moves forward.

### RESULT (primary key)

This field captures the outcome of the appeal. The result is usually represented in clear text, such as "appeal rejected" or "appeal allowed," offering an explicit understanding of the decision made by the appeal body.

In [6]:
q = db.query(
    REG125_APPEAL.result
).distinct()

res = patstat.df(q)
res

                                           result
0                              REMITTAL FOR GRANT
1               APPEAL OF PROPRIETOR INADMISSIBLE
2                       WITHDRAWAL OF APPLICATION
3                     MAINTENANCE IN AMENDED FORM
4           WITHDRAWAL OF APPEAL OF THE APPLICANT
5            WITHDRAWAL OF APPEAL OF THE OPPONENT
6           CONTINUATION OF EXAMINATION PROCEDURE
7    REVOCATION OF PATENT AT PROPRIETOR'S REQUEST
8       APPEAL OF OPPONENT DEEMED NOT TO BE FILED
9                             REJECTION OF APPEAL
10     APPEAL OF APPLICANT DEEMED NOT TO BE FILED
11    APPEAL OF PROPRIETOR DEEMED NOT TO BE FILED
12                                             T2
13  WITHDRAWAL OF APPEAL OF THE PATENT PROPRIETOR
14                  APPEAL OF PROPRIETOR REJECTED
15            CLOSURE OF THE OPPOSITION PROCEDURE
16                      INADMISSIBILITY OF APPEAL
17                            ALLOWANCE OF APPEAL
18                APPEAL OF OPPONENT INADMISSIBLE
19           APPEAL DEEMED NOT TO HAVE BEEN FILED
20             APPLICATION DEEMED TO BE WITHDRAWN
21                       REVOCATION OF THE PATENT
22                    APPEAL OF OPPONENT REJECTED
23
24                   APPEAL OF APPLICANT REJECTED
25           CONTINUATION OF OPPOSITION PROCEDURE
26                  MAINTENANCE IN UNAMENDED FORM
27                         OTHER KIND OF DISPOSAL
28               APPEAL OF APPLICANT INADMISSIBLE
29                           WITHDRAWAL OF APPEAL

### RESULT_DATE (primary key)

The date when the appeal’s outcome was finalised. This is important for understanding when the appeal's result was officially communicated and for tracking the overall length of the appeal process.