# The REG127_PETITION_RVW: petition review table

Welcome to a comprehensive exploration of one of the tables in the PATSTAT database: the ``REG127_PETITION_RVW`` table. This table keeps track of petitions to review the outcomes of appeals under the European Patent Convention (EPC), providing insights into the legal process and the procedural steps taken after an appeal decision is made.

The ``REG127_PETITION_RVW`` table contains detailed information regarding petitions filed to review the outcome of an appeal. Petitions for review are a crucial part of the legal process outlined in Rules 104 to 108 EPC, allowing parties to challenge the decision of an appeal. An individual application may have one or more petitions for review associated with it, particularly if the decision made in an appeal is contested.

This data is key for understanding the review process in the European patent system, shedding light on how appeal decisions are revisited and reconsidered.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG127_PETITION_RVW, REG101_APPLN, REG125_APPEAL
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

In [2]:
q = db.query(
    REG127_PETITION_RVW.id,
    REG127_PETITION_RVW.review_nr,
    REG127_PETITION_RVW.appeal_nr,
    REG127_PETITION_RVW.review_date,
    REG127_PETITION_RVW.petitioner_code,
    REG127_PETITION_RVW.review_decision_date,
    REG127_PETITION_RVW.review_kind
)

res = patstat.df(q)
res

,id,review_nr,appeal_nr,review_date,petitioner_code,review_decision_date,review_kind
0,16786952,R0015/24,T1159/22-3202,2024-07-21,APPR,9999-12-31,
1,5012133,R0019/13,T0473/09-3307,2013-08-08,APPR,9999-12-31,
2,19710182,R0028/24,T0289/23-3507,2024-11-08,APPR,9999-12-31,
3,15164122,R0012/24,T0597/21-3201,2024-01-22,APPR,9999-12-31,
4,18814732,R0025/24,T2165/22-3402,2024-11-08,APPR,9999-12-31,
...,...,...,...,...,...,...,...
275,108480,R0009/13,T1760/11-3301,2013-05-14,OP04,2014-02-10,Petition for review obviously unsubstantiated ...
276,108480,R0005/13,T1760/11-3301,2013-05-03,OP06,2014-02-10,Petition for review obviously unsubstantiated ...
277,108480,R0012/13,T1760/11-3301,2013-05-16,OP07,2014-02-10,Petition for review obviously unsubstantiated ...
278,10006835,R0015/22,T0980/19-3302,2022-06-27,OP09,9999-12-31,
279,108480,R0013/13,T1760/11-3301,2013-05-16,OP10,2014-02-10,Petition for review obviously unsubstantiated ...

## Key fields in the ``REG127_PETITION_RVW`` table

### ID

It serves as the foreign key when linking the petition data with other tables, such as `REG101_APPLN`.

### REVIEW_NR (primary key)

The internal identification number assigned to the petition for review. It serves as a unique identifier for each review petition filed.

### APPEAL_NR
The appeal number associated with the petition, linking the petition for review to the appeal decision that is being contested.

In [3]:
q = db.query(
    REG127_PETITION_RVW.id,
    REG127_PETITION_RVW.review_nr,
    REG127_PETITION_RVW.appeal_nr,
    REG125_APPEAL.appeal_date,
    REG125_APPEAL.phase,
    REG125_APPEAL.result,
    REG127_PETITION_RVW.review_date,
    REG127_PETITION_RVW.petitioner_code,
    REG127_PETITION_RVW.review_decision_date,
    REG127_PETITION_RVW.review_kind
).join(
    REG125_APPEAL, REG127_PETITION_RVW.appeal_nr == REG125_APPEAL.appeal_nr  # Join on appeal_nr
)

res = patstat.df(q)
res

,id,review_nr,appeal_nr,appeal_date,phase,result,review_date,petitioner_code,review_decision_date,review_kind
0,97109195,R0001/17,T1789/12-3402,2012-08-08,opposition,APPEAL OF OPPONENT REJECTED,2017-02-07,OP01,2018-07-10,Petition for review obviously unsubstantiated ...
1,94115175,R0011/08,T0221/06-3402,2006-02-15,opposition,REVOCATION OF THE PATENT,2008-12-08,APPR,2009-04-06,Petition for review obviously unsubstantiated ...
2,5787397,R0002/17,T1322/15-3203,2015-06-26,opposition,REVOCATION OF THE PATENT,2017-05-10,APPR,2018-04-05,Withdrawal of the petition for review.
3,8101643,R0005/19,T2378/13-3502,2013-11-22,opposition,MAINTENANCE IN AMENDED FORM,9999-12-31,OP01,2021-03-15,Petition for review allowed and re-opening of ...
4,8745686,R0003/24,T1656/17-3504,2017-07-24,opposition,APPEAL OF PROPRIETOR REJECTED,2024-01-09,APPR,9999-12-31,
...,...,...,...,...,...,...,...,...,...,...
362,10185812,R0009/21,T3272/19-3303,2019-12-18,opposition,CONTINUATION OF OPPOSITION PROCEDURE,9999-12-31,APPR,2022-06-28,Petition for review obviously inadmissible (no...
363,9711390,R0008/21,T0777/17-3304,2017-03-23,opposition,REVOCATION OF THE PATENT,2021-06-07,APPR,2022-05-30,Petition for review obviously inadmissible (no...
364,95916308,R0010/09,T1515/06-3202,2006-09-27,opposition,REVOCATION OF THE PATENT,2009-06-16,APPR,2010-06-22,Petition for review obviously unsubstantiated ...
365,13727040,R0007/22,T0779/18-3307,2018-03-22,opposition,APPEAL OF PROPRIETOR REJECTED,2022-03-31,APPR,9999-12-31,
366,3736588,R0006/18,T0611/15-3502,2015-03-20,opposition,REVOCATION OF THE PATENT,2018-04-23,APPR,2019-02-20,Petition for review obviously unsubstantiated ...

### REVIEW_DATE
The date when the petition for review was filed. This is an essential timestamp that marks the initiation of the petition process.

### PETITIONER_CODE
The code that identifies the petitioner, such as "APPR" for the applicant or proprietor or "OP01" for the first opponent. This code is crucial for identifying who is challenging the appeal decision.

In [4]:
q = db.query(
    REG127_PETITION_RVW.petitioner_code
).distinct()

res = patstat.df(q)
res

  petitioner_code
0            APPR
1            OP01
2            OP02
3            OP03
4            OP04
5            OP06
6            OP07
7            OP09
8            OP10

### REVIEW_DECISION_DATE
The date when the decision regarding the petition for review was made. This marks the final outcome of the petition.

### REVIEW_KIND
A description of the kind of decision made in response to the review petition, providing further details on whether the appeal decision was upheld, overturned, or amended.

In [5]:
q = db.query(
    REG127_PETITION_RVW.review_kind
).distinct()

res = patstat.df(q)
res

                                         review_kind
0
1  Petition for review allowed and re-opening of ...
2  Petition for review obviously inadmissible (no...
3  Petition for review obviously unsubstantiated ...
4                  Rejection of petition for review.
5             Withdrawal of the petition for review.
6                  Petition for review inadmissible.