# The REG106_PRIOR table

Welcome to table **REG106_PRIOR**. As the name suggests, this table contains the data of the claimed priorities. In particular, it includes information about the authority, the priority kind, publication in the European Patent Bulletin, among others.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG106_PRIOR
from sqlalchemy import func
import pandas as pd

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

## ID (Primary Key)

Technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
i = db.query(
    REG106_PRIOR.id
).limit(1000)

df = patstat.df(i)
df

           id
0    13854686
1    13708724
2    13831773
3    10810545
4     5017926
..        ...
995  23737031
996  24162853
997  98925292
998  89312241
999  24770101

[1000 rows x 1 columns]

## CHANGE_DATE

It is the date on which the record was saved in the database.

In [3]:
change_date = db.query(
    REG106_PRIOR.change_date,
    REG106_PRIOR.id
).limit(100)

change_date_df = patstat.df(change_date)
change_date_df

   change_date        id
0   2017-02-24  15711002
1   2009-01-23   7796069
2   2014-05-16  12751466
3   2022-08-23  20864464
4   2024-12-14  24730714
..         ...       ...
95  2019-10-25  17867389
96  2004-07-23   2792608
97  1993-10-01  92904689
98  2006-02-17   5021537
99  2017-04-21  15762708

[100 rows x 2 columns]

## BULLETIN_YEAR

For actions that have been published in the European Patent Bulletin, it is the year of the publication in the European Patent Bulletin. The default value is 0, used for applications that are not published or for which the year is not known. The format is YYYY otherwise.

In [4]:
years = db.query(
    REG106_PRIOR.bulletin_year,
    REG106_PRIOR.id
).limit(1000)

years_df = patstat.df(years)
years_df

     bulletin_year        id
0             2017  15711002
1             2009   7796069
2             2014  12751466
3                0  20864464
4                0  24730714
..             ...       ...
995              0   1995007
996           1984  83109419
997           2005   4028499
998           1982  81303412
999           2006   4786831

[1000 rows x 2 columns]

## BULLETIN_NR

This is the issue number of the European Patent Bulletin for actions that have been published in it. This attribute indicates the calendar week the European Patent Bulletin was published. The default value 0 is used when the attribute `bulletin_year` is 0.

In [5]:
bulletin_nr = db.query(
    REG106_PRIOR.id,
    REG106_PRIOR.bulletin_nr,
    REG106_PRIOR.bulletin_year
).limit(100)

bulletin_nr_df = patstat.df(bulletin_nr)
bulletin_nr_df

          id  bulletin_nr  bulletin_year
0   14788128            0              0
1   24845284            0              0
2    8833716            0              0
3   17796802            0              0
4   17900774            0              0
..       ...          ...            ...
95  91114907           12           1992
96  98946626            0              0
97  20811693           40           2022
98  16918525            0              0
99   5769348            0              0

[100 rows x 3 columns]

## PRIOR_SEQ_NR

The ordinal number of the priority in the application where it is claimed. If one or more priorities are given, then they are numbered starting from one. In case the priority rights have been lost, then there will be one entry with PRIOR_SEQ_NR = 0.

In [6]:
prior_seq = db.query(
    REG106_PRIOR.id,
    REG106_PRIOR.prior_seq_nr
).order_by(
    REG106_PRIOR.prior_seq_nr
).limit(50000)

prior_seq_df = patstat.df(prior_seq)
prior_seq_df

             id  prior_seq_nr
0      10861188             0
1      12709779             0
2      89402310             0
3      85900766             0
4      78101803             0
...         ...           ...
49995  11004198             1
49996  21906150             1
49997  96305757             1
49998   6723685             1
49999  15763986             1

[50000 rows x 2 columns]

We can count how many applications correspond to a specific priority sequence number.

In [7]:
tot_seq = db.query(
    REG106_PRIOR.prior_seq_nr,
    func.count(REG106_PRIOR.id).label('number_of_applications')
).group_by(
    REG106_PRIOR.prior_seq_nr
).order_by(
    REG106_PRIOR.prior_seq_nr
)

tot_seq_df = patstat.df(tot_seq)
tot_seq_df

     prior_seq_nr  number_of_applications
0               0                    7123
1               1                 6441300
2               2                 1042341
3               3                  270673
4               4                  119642
..            ...                     ...
415           415                       1
416           416                       1
417           417                       1
418           418                       1
419           419                       1

[420 rows x 2 columns]

## PRIOR_KIND

Priority kind. It can be "national", "regional" or "international".

In [8]:
kind = db.query(
    REG106_PRIOR.prior_kind,
    func.count(REG106_PRIOR.id).label('number_of_applications')
).group_by(
    REG106_PRIOR.prior_kind
).order_by(
    func.count(REG106_PRIOR.id)
)

kind_df = patstat.df(kind)
kind_df

      prior_kind  number_of_applications
0  international                   62104
1       regional                  345939
2       national                 7707187

## PRIOR_AUTH

Authority of the priority document.

Let's count how many priorities for each patent authority, as of now, there are in PATSTAT.

In [9]:
auth = db.query(
    REG106_PRIOR.prior_auth,
    func.count(REG106_PRIOR.id).label('number_of_applications')
).group_by(
    REG106_PRIOR.prior_auth
).order_by(
    func.count(REG106_PRIOR.id).label('number_of_applications').desc()
)

auth_df = patstat.df(auth)
auth_df

    prior_auth  number_of_applications
0           US                 2998634
1           JP                 1434246
2           DE                  832400
3           CN                  632972
4           KR                  407212
..         ...                     ...
154         GD                       1
155         AO                       1
156         JM                       1
157         TG                       1
158         TZ                       1

[159 rows x 2 columns]

## PRIOR_NR

Number of the priority document or indicator that the priority rights have been lost. The domain consists of up to fifteen characters: number of priority application or the string ‘deleted’.

In [10]:
publn_nr = db.query(
    REG106_PRIOR.prior_nr,
    REG106_PRIOR.prior_auth
).limit(1000)

publn_nr_df = patstat.df(publn_nr)
publn_nr_df

          prior_nr prior_auth
0     201414252789         US
1      20230121699         JP
2      20070255216         JP
3    201662352972P         US
4     201710147619         CN
..             ...        ...
995    20140244712         JP
996    20150019390         JP
997    20190202477         EP
998    2005PI03756         BR
999    20190021995         KR

[1000 rows x 2 columns]

## PRIOR_DATE

 Filing date of the priority document.

In [11]:
publn_date = db.query(
    REG106_PRIOR.prior_nr,
    REG106_PRIOR.prior_date
).limit(1000)

publn_date_df = patstat.df(publn_date)
publn_date_df

         prior_nr  prior_date
0     19980007265  1998-01-14
1     20101017057  2010-05-21
2     20180050586  2018-05-18
3     20170129093  2017-10-10
4    20040560657P  2004-04-08
..            ...         ...
995   20200207834  2020-11-16
996   20050114584  2005-04-12
997   19910107625  1991-05-13
998  20090262395P  2009-11-18
999  202217714550  2022-04-06

[1000 rows x 2 columns]