# The REG128_LIMITATION: request for limitation table

Welcome to an in-depth exploration of the `REG128_LIMITATION table`. This table holds crucial information related to the filing, allowance, and rejection of requests for limitation under the European Patent Convention (EPC), specifically Rules 90 to 95. A request for limitation involves a procedure where a patent proprietor can request to limit the scope of a patent, either voluntarily or following opposition or revocation proceedings.

This table is key for understanding the processes involved in limiting patents, including how decisions are made and communicated, as well as tracking the impact of such decisions on patent validity.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG128_LIMITATION, REG101_APPLN
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

In [2]:
q = db.query(
    REG128_LIMITATION.id,
    REG128_LIMITATION.limit_seq_nr,
    REG128_LIMITATION.limitation_filing_date,
    REG128_LIMITATION.limitation_filing_decision,
    REG128_LIMITATION.date_dispatch_allowance,
    REG128_LIMITATION.date_payment_allowance,
    REG128_LIMITATION.date_dispatch_rejection,
    REG128_LIMITATION.date_legal_effect_rejection
)

res = patstat.df(q)
res

,id,limit_seq_nr,limitation_filing_date,limitation_filing_decision,date_dispatch_allowance,date_payment_allowance,date_dispatch_rejection,date_legal_effect_rejection
0,92905727,1,2009-10-26,inadmissible,9999-12-31,9999-12-31,2010-08-31,9999-12-31
1,17915016,1,2024-03-06,,9999-12-31,9999-12-31,9999-12-31,9999-12-31
2,97121146,1,2007-12-13,admissible,2008-03-28,2008-04-02,9999-12-31,9999-12-31
3,88908134,1,2007-12-17,admissible,2008-05-16,2008-05-28,9999-12-31,9999-12-31
4,91916479,1,2007-12-20,admissible,2008-05-16,2008-05-28,9999-12-31,9999-12-31
...,...,...,...,...,...,...,...,...
674,1273812,1,2008-02-01,withdrawn,9999-12-31,9999-12-31,9999-12-31,9999-12-31
675,1939659,2,2015-12-16,withdrawn,9999-12-31,9999-12-31,9999-12-31,9999-12-31
676,8735675,1,2015-06-10,withdrawn,9999-12-31,9999-12-31,9999-12-31,9999-12-31
677,18721888,1,2021-03-11,withdrawn,9999-12-31,9999-12-31,9999-12-31,9999-12-31
678,10765923,1,2021-10-21,withdrawn,9999-12-31,9999-12-31,9999-12-31,9999-12-31

## Key fields in the REG128_LIMITATION table

### ID (primary key)
The ID field serves as a technical identifier that uniquely connects patent applications across various tables.

### LIMIT_SEQ_NR (sequence number of limitation request) (primary key)
The ``LIMIT_SEQ_NR`` is a unique sequence number assigned to each limitation request filed for a particular patent application. This number helps distinguish between multiple limitation requests for the same application. It typically ranges from 1 to 10, with each request getting a new sequence number, starting from 1. This allows the tracking of all limitation requests, even if there are multiple for the same application.

### Limitation filing date (filing date of limitation request)
The ``LIMITATION_FILING_DATE`` records the date on which the request for limitation was officially filed. This date marks the beginning of the limitation procedure, during which the applicant seeks to restrict the scope of the patent claims. It is a crucial timestamp for understanding when the process started.

### Limitation filing decision (decision on limitation request)
The ``LIMITATION_FILING_DECISION``indicates the decision made regarding the admissibility of the limitation request. It reflects whether the request for limitation was accepted for further processing or whether it was deemed inadmissible. This decision is important as it determines whether the limitation procedure will proceed.

In [3]:
q = db.query(
    REG128_LIMITATION.limitation_filing_decision
).distinct()

res = patstat.df(q)
res

                         limitation_filing_decision
0                                      inadmissible
1
2                                        admissible
3  deemed not to be filed, Opposition pending/filed
4                                         withdrawn

### DATE_DISPATCH_ALLOWANCE (Dispatch date of limitation allowance)

The ``DATE_DISPATCH_ALLOWANCE`` marks the date when the intention to limit the patent was officially dispatched. It is the point at which the request for limitation has been accepted, and the applicant is informed of the allowance, signalling the acceptance of the limitation procedure.

### DATE_PAYMENT_ALLOWANCE (payment date of limitation fee)

The ``DATE_PAYMENT_ALLOWANCE`` indicates the date on which the payment for the publication fee associated with the new limited specification was made. After a limitation request is allowed, this payment ensures that the updated patent specification, reflecting the limited claims, is published. This fee is a necessary part of the procedure to finalise the limitation.

### Date dispatch rejection (dispatch date of limitation rejection)
The ``DATE_DISPATCH_REJECTION`` refers to the date when the decision to reject a limitation request was formally dispatched. If the limitation request is found to be unfeasible or invalid, this date represents the formal communication of that rejection to the applicant.

### Date legal effect rejection (legal effect date of limitation rejection)
The DATE_LEGAL_EFFECT_REJECTION captures the date when the rejection of a limitation request takes legal effect. This date signifies when the legal status of the application or patent is officially altered due to the rejection, preventing the requested limitation from being implemented.