# The REG202_PROC_STEP_TEXT table

Welcome to the ``REG202_PROC_STEP_TEXT`` table overview. The ``REG202_PROC_STEP_TEXT`` table contains detailed textual information related to procedural steps from the ``REG201_PROC_STEP`` table, offering additional context and explanations for each step. These texts provide valuable insights into the nature of procedural steps throughout the patent granting procedure, helping to clarify the status or actions involved. Each record captures a specific text linked to a procedural step, along with its type, which defines the role or category of the text.

While ``REG201_PROC_STEP`` records structured data on procedural actions, the ``REG202_PROC_STEP_TEXT`` table enriches this information with explanatory texts that help users interpret the significance of each step. Each record is categorised by the ``STEP_TEXT_TYPE`` attribute, which defines the role of the text, whether it describes the step itself, references a particular year, or details extension states. This added layer of context is particularly valuable for analysts, researchers, and policymakers who need deeper insights beyond numeric codes and classifications. By integrating procedural data with descriptive text, the table enhances transparency and supports a more comprehensive understanding of the patent process.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG201_PROC_STEP, REG101_APPLN, REG202_PROC_STEP_TEXT
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

## Key fields in the REG202_PROC_STEP_TEXT table

### ID (primary key)
A technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.
### STEP_ID
The ``STEP_ID`` is a unique identifier assigned to each procedural step within the patent application process. It is present in multiple tables, including ``REG201_PROC_STEP``, ``REG202_PROC_STEP_TEXT``, ``REG203_PROC_STEP_DATE``, ``REG721_PROC_STEP``, ``REG722_PROC_STEP_TEXT``, and ``REG723_PROC_STEP_DATE``. This attribute serves as a key reference for identifying and linking procedural steps across various datasets. With a domain of up to 30 characters, it ensures precise tracking and organization of procedural events associated with patent applications.
### STEP_TEXT
The ``STEP_TEXT`` attribute represents the text associated with a procedural step in the patent process. It provides a description or explanation related to the specific procedural step identified in the ``REG201_PROC_STEP`` table. This text can offer additional details or context about the step, helping users better understand its significance and actions. The field can contain up to approximately 300 characters, and if no description is available, the value is left as an empty string.
### STEP_TEXT_TYPE
The ``STEP_TEXT_TYPE`` attribute defines the type of text associated with a procedural step. It categorizes the text in terms of its content or purpose, such as a description of the step, specific year references, or details about extension states. The text type helps users identify the context in which the text is used. The field allows up to 30 characters and does not have a default value. Examples of possible text types include “STEP_DESCRIPTION,” “YEAR,” and “Extension states”.

In [2]:
q = db.query(
    REG202_PROC_STEP_TEXT.id,
    REG202_PROC_STEP_TEXT.step_id,
    REG202_PROC_STEP_TEXT.step_text,
    REG202_PROC_STEP_TEXT.step_text_type,
    REG201_PROC_STEP.step_phase,
    REG201_PROC_STEP.step_result,
    REG201_PROC_STEP.step_country,
    REG201_PROC_STEP.time_limit
).join(
    REG201_PROC_STEP,
    REG202_PROC_STEP_TEXT.step_id == REG201_PROC_STEP.step_id
).limit(1000)

res = patstat.df(q)
res

,id,step_id,step_text,step_text_type,step_phase,step_result,step_country,time_limit
0,24758953,STEP_VAPT_6226879,Validation of the patent,STEP_DESCRIPTION,EXAMN,,,
1,23786599,STEP_PROL_5558553,de,procedure language,EXAMN,,,
2,17716054,RENEWAL_8979147,Renewal fee payment,STEP_DESCRIPTION,UNDEF,,,
3,89910677,STEP_ADWI_3292210,fee for grant / fee for printing not paid in time,STEP_DESCRIPTION_NAME,EXAMN,,,
4,93906743,STEP_PFEE_3716894,Penalty fee Rule 85a EPC 1973,STEP_DESCRIPTION,EXAMN,,,01
...,...,...,...,...,...,...,...,...
995,14707301,STEP_3905968,Payment of the first designation fee,STEP_DESCRIPTION,REGEN,,,
996,911934,STEP_23288,Payment of the fee for supplementary search,STEP_DESCRIPTION,REGEN,,,
997,17927131,STEP_5268775,Payment of the fee for supplementary search,STEP_DESCRIPTION,REGEN,,,
998,16750727,STEP_VAPT_360086,MD,Validation states,EXAMN,,,
999,12197578,RENEWAL_6333634,Renewal fee payment,STEP_DESCRIPTION,UNDEF,,,

We can show the list of distinct step text types.

In [3]:
q = db.query(
    REG202_PROC_STEP_TEXT.step_text_type
).distinct()

res = patstat.df(q)
res

           step_text_type
0      procedure language
1                approval
2     STEP_IDENTIFICATION
3        Extension states
4                    YEAR
5       Validation states
6                 COUNTRY
7       Kind of amendment
8         sequence-number
9     searching authority
10  STEP_DESCRIPTION_NAME
11     APPLICATION_NUMBER
12       STEP_DESCRIPTION
13        kind of refusal