# The REG203_PROC_STEP_DATE: date of procedural step table

Welcome to the ``REG203_PROC_STEP_DATE`` table overview. The ``REG203_PROC_STEP_DATE`` table contains important date information related to procedural steps in the European patent granting process. Specifically, it stores the dates of each procedural step, providing essential temporal data such as when certain actions within the patent granting process took place. Each record links a procedural step to its respective date, which helps track the timeline of the patent application process. This table is crucial for understanding the sequence of events and deadlines, adding another layer of detail to the procedural steps.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG201_PROC_STEP, REG101_APPLN, REG202_PROC_STEP_TEXT, REG203_PROC_STEP_DATE
from sqlalchemy import select, func, case, select, and_

patstat = PatstatClient(env='PROD')

db = patstat.orm()

## Key fields in the REG203_PROC_STEP_DATE table

### ID (primary key)
A technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
q = db.query(
    REG203_PROC_STEP_DATE.id
).limit(100)

res = patstat.df(q)
res

          id
0    4727162
1    3425219
2   18150571
3   80302968
4   17822782
..       ...
95  17895400
96   6125793
97  13723785
98   2703009
99   1991295

[100 rows x 1 columns]

### STEP_ID (primary key)
The STEP_ID is a unique identifier assigned to each procedural step within the patent application process. It is present in multiple tables, including REG201_PROC_STEP, REG202_PROC_STEP_TEXT, REG203_PROC_STEP_DATE, REG721_PROC_STEP, REG722_PROC_STEP_TEXT, and REG723_PROC_STEP_DATE. This attribute serves as a key reference for identifying and linking procedural steps across various datasets. With a domain of up to 30 characters, it ensures precise tracking and organisation of procedural events associated with patent applications.

### STEP_DATE (primary key)
The STEP_DATE attribute represents the date associated with a procedural step in the patent process. It captures the specific date when a particular procedural step occurred, providing essential temporal information for each step's timeline. This attribute helps to track the progression of a patent through the various procedural phases. It does not have a default value, as each procedural step must be linked to an actual date. The date format follows standard conventions, ensuring consistency in documenting and analysing the chronological sequence of patent steps.

### STEP_DATE_TYPE (primary key)
The STEP_DATE_TYPE attribute describes the specific type of date related to a procedural step in the patent process. It identifies the role or event associated with the date, providing a deeper understanding of the timing and context of the step:
– CANCT: date of cancellation
– DISPA: date of dispatch
– DRAEX: decision date of request for accelerated examination (RAEX)
– EFFEC: date effective
– GRNTF: grant fee paid
– LAPPR: date of later approval
– PAYM1: date of payment 1
– PAYMN: date of payment
– PRNTF: print fee paid
– RAEXA: date of request for accelerated examination (RAEX)
– RECPT: date of receipt
– REPLY: date of reply
– REQST: date of request
– RESLT: result date
– TCLMS: translation of claims
– WV713: waiver agreement, according to rule 71(3)
– DTREG: date of registration
– DTDEC: date of decision
– DTNOT: date of notification
– LCNSC: date of licence commitment
– DTREC: date of receipt
– WDRWL: date of withdrawal
– FIACT: date of filing action
– FIDEC: date of filing decision
– FIAPP: date of filing appeal

In [3]:
q = db.query(
    REG203_PROC_STEP_DATE.id,
    REG203_PROC_STEP_DATE.step_id,
    REG203_PROC_STEP_DATE.step_date,
    REG203_PROC_STEP_DATE.step_date_type,
    REG201_PROC_STEP.step_phase,
    REG201_PROC_STEP.step_result
).join(
    REG203_PROC_STEP_DATE, REG201_PROC_STEP.id == REG203_PROC_STEP_DATE.id
).limit(100)

res = patstat.df(q)
res

,id,step_id,step_date,step_date_type,step_phase,step_result
0,18878610,STEP_ABEX_22052831,2021-06-10,REQST,UNDEF,
1,18878610,STEP_IGRA_1825984,2024-09-02,DISPA,UNDEF,
2,18878610,STEP_EXRE_2536381,2023-10-18,REPLY,UNDEF,
3,18878610,STEP_IGRA_1825984,2025-01-02,PRNTF,UNDEF,
4,18878610,STEP_IGRA_1825984,2025-01-02,GRNTF,UNDEF,
...,...,...,...,...,...,...
95,99120994,STEP_EXRE_3917430,2001-05-09,REPLY,EXAMN,
96,99120994,STEP_EXRE_3917431,2001-08-10,DISPA,EXAMN,
97,99120994,STEP_IGRA_2769072,2003-02-10,PRNTF,EXAMN,
98,5013996,STEP_EXRE_664578,2006-06-09,DISPA,REGEN,
99,5013996,RENEWAL_2343736,2007-06-27,PAYMN,REGEN,

Let's see the distinct types of step date.

In [4]:
q = db.query(
    REG203_PROC_STEP_DATE.step_date_type
).distinct()

res = patstat.df(q)
res

   step_date_type
0           PAYMN
1           RECPT
2           EFFEC
3           DISPA
4           RESLT
5           REPLY
6           CANCT
7           PRNTF
8           DRAEX
9           REQST
10          PAYM1
11          WV713
12          LAPPR
13          TCLMS
14          GRNTF
15          RAEXA