# Unitary Patent procedural data: `REG722_PROC_STEP_TEXT`
The `REG722_PROC_STEP_TEXT` table contains a short explanation or more detailed information about each procedural step from the `REG721_PROC_STEP` table, offering additional context and explanations for each step. 
Let’s break down the key fields in this table. The first step as usual is to initialise the PATSTAT client and import the table.

In [12]:
from epo.tipdata.patstat import PatstatClient

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

# Importing the as models
from epo.tipdata.patstat.database.models import REG722_PROC_STEP_TEXT,REG721_PROC_STEP

# Importing sql alchemy package
from sqlalchemy import func

## Key fields in the `REG722_PROC_STEP_TEXT` table
* `ID` (primary key): a technical identifier for the Unitary Patent, without business meaning.
* `STEP_ID`: this attribute contains IDs identifying a procedural step.
* `STEP_TEXT`: this attribute contains a text related to the procedural step. It provides a description or explanation related to the specific procedural step identified in the `REG721_PROC_STEP table`. This text offers additional details or context about the step, helping users better understand its purpose and associated actions.
* `STEP_TEXT_TYPE`: this attribute specifies the type of text associated with the procedural step. It categorizes the text according to its content or purpose, such as a description of the step, references to specific years, or details about extension states. The text type helps users understand the context in which the text is used.

Let's plot the table to visualize its structure.

In [9]:
reg722 = (
    db.query(
         REG722_PROC_STEP_TEXT.id,
         REG722_PROC_STEP_TEXT.step_id,
         REG722_PROC_STEP_TEXT.step_text,
         REG722_PROC_STEP_TEXT.step_text_type,
    )
    .order_by( REG722_PROC_STEP_TEXT.id)
    .limit(10000)
)

reg722_df = patstat.df(reg722)
reg722_df

,id,step_id,step_text,step_text_type
0,5018904,STEP_UP_UDEC_6,Date and purport of the decision on the regist...,STEP_DESCRIPTION
1,5018904,STEP_UP_UDFI_5,The request for unitary effects,STEP_DESCRIPTION
2,5701869,STEP_UP_UDFI_1,The request for unitary effects,STEP_DESCRIPTION
3,5701869,STEP_UP_UDWI_2,Date of receipt of withdrawal of Request for U...,STEP_DESCRIPTION
4,6748170,STEP_UP_UDWI_10,Date of receipt of withdrawal of Request for U...,STEP_DESCRIPTION
...,...,...,...,...
9995,14800855,STEP_UP_RFEE_11830,12,YEAR
9996,14800855,STEP_UP_UREG_11828,"AT, BE, BG, DE, DK, EE, FI, FR, IT, LT, LU, LV...",UNITARY_STATES
9997,14801009,STEP_UP_UDEC_11882,Date and purport of the decision on the regist...,STEP_DESCRIPTION
9998,14801009,STEP_UP_RFEE_11884,Renewal fee payment,STEP_DESCRIPTION
9999,14801009,STEP_UP_UREG_11883,Date of registration of unitary effect,STEP_DESCRIPTION

Let’s join the `REG722_PROC_STEP_TEXT` table with the `REG721_PROC_STEP` table to obtain a more complete overview of the information related to each procedural step.

In [11]:
reg722 = (
    db.query(
         REG722_PROC_STEP_TEXT.id,
         #REG722_PROC_STEP_TEXT.step_id,
         REG722_PROC_STEP_TEXT.step_text,
         REG722_PROC_STEP_TEXT.step_text_type,
         REG721_PROC_STEP.id,
         REG721_PROC_STEP.step_id,
         REG721_PROC_STEP.step_phase,
         REG721_PROC_STEP.step_code,
         REG721_PROC_STEP.step_result,
         REG721_PROC_STEP.step_result_type,
    ).join(
         REG722_PROC_STEP_TEXT,
        REG722_PROC_STEP_TEXT.id== REG721_PROC_STEP.id
            
    ).order_by(REG721_PROC_STEP.id)
    .limit(10000)
)

reg722_df = patstat.df(reg722)
reg722_df

,id,step_text,step_text_type,id,step_id,step_phase,step_code,step_result,step_result_type
0,5018904,Date and purport of the decision on the regist...,STEP_DESCRIPTION,5018904,STEP_UP_UDEC_6,UNIP,UDEC,Negative,
1,5018904,The request for unitary effects,STEP_DESCRIPTION,5018904,STEP_UP_UDFI_5,UNIP,UDFI,,
2,5018904,The request for unitary effects,STEP_DESCRIPTION,5018904,STEP_UP_UDEC_6,UNIP,UDEC,Negative,
3,5018904,Date and purport of the decision on the regist...,STEP_DESCRIPTION,5018904,STEP_UP_UDFI_5,UNIP,UDFI,,
4,5701869,Date of receipt of withdrawal of Request for U...,STEP_DESCRIPTION,5701869,STEP_UP_UDFI_1,UNIP,UDFI,,
...,...,...,...,...,...,...,...,...,...
9995,11830263,Renewal fee payment,STEP_DESCRIPTION,11830263,STEP_UP_UDEC_2293,UNIP,UDEC,Positive,
9996,11830263,Date of registration of unitary effect,STEP_DESCRIPTION,11830263,STEP_UP_UDEC_2293,UNIP,UDEC,Positive,
9997,11830263,"AT, BE, BG, DE, DK, EE, FI, FR, IT, LT, LU, LV...",UNITARY_STATES,11830263,STEP_UP_UDEC_2293,UNIP,UDEC,Positive,
9998,11830263,The request for unitary effects,STEP_DESCRIPTION,11830263,STEP_UP_UDEC_2293,UNIP,UDEC,Positive,
9999,11830263,Date and purport of the decision on the regist...,STEP_DESCRIPTION,11830263,STEP_UP_RFEE_2295,UNIP,RFEE,,