# Unitary patents country licenses: `REG712_LICENSEE_STATES`
The table `REG712_LICENSEE_STATES` contains the countries for which a license is valid.
Let’s break down the key fields in this table. The first step as usual is to initialise the PATSTAT client and import the table.

In [1]:
from epo.tipdata.patstat import PatstatClient

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

# Importing the as models
from epo.tipdata.patstat.database.models import REG712_LICENSEE_STATES, REG711_LICENSEE

# Importing sql alchemy package
from sqlalchemy import func

## Key fields in table `REG712_LICENSEE_STATES`
* `ID` (primary key): a technical identifier for the Unitary Patent, without business meaning.
* `BULLETIN_YEAR`: this attribute indicates the year of the publication in the European Patent Bulletin.
* `BULLETIN_NR`: this attribute indicates the calendar week in which the European Patent Bulletin has been published.
* `LICENSEE_SEQ_NR`: this atribute contins the serial number of license / sub-license. The first two digits identify the serial number of the main licence, while the optional additional two digits indicate the serial number of a sub-licence. Both main licences and sub-licences can have a maximum serial number of 10.
* `LICENSEE_COUNTRY`: this attribute lists the countries or territories where the license is valid, in case it does not apply to all designated states.

Let's plot the table to visualise its structure.

In [2]:
reg712 = (
    db.query(
        REG712_LICENSEE_STATES.id,
        REG712_LICENSEE_STATES.bulletin_year,
        REG712_LICENSEE_STATES.bulletin_nr,
        REG712_LICENSEE_STATES.licensee_seq_nr,
        REG712_LICENSEE_STATES.licensee_country,
    )
    .order_by(REG712_LICENSEE_STATES.id)
    .limit(10000)
)

reg712_df = patstat.df(reg712)
reg712_df

           id  bulletin_year  bulletin_nr licensee_seq_nr licensee_country
0     9770708              0            0              03               DE
1     9770708              0            0              03               BG
2     9770708              0            0              03               MT
3     9770708              0            0              03               DK
4     9770708              0            0              03               PT
..        ...            ...          ...             ...              ...
735  23170155              0            0              02               PT
736  23170155              0            0              02               NL
737  23170155              0            0              02               LU
738  23170155              0            0              02               IT
739  23170155              0            0              02               BE

[740 rows x 5 columns]

## NOTE 
Licenses that are valid only in a subset of the countries where the patent is valid can be identified as follows: in the `REG711_LICENSEE` table, these licenses have the value ‘as-indicated’ in the `DESIGNATION` attribute. In order to see this, let's merge the ` REG712_LICENSEE_STATES`with the`REG711_LICENSEE`and retrieve the `DESIGNATION` attribute for each `ID`.

In [3]:
Des = (
    db.query(
        REG712_LICENSEE_STATES.id,
        REG712_LICENSEE_STATES.bulletin_year,
        REG712_LICENSEE_STATES.bulletin_nr,
        REG712_LICENSEE_STATES.licensee_seq_nr,
        REG712_LICENSEE_STATES.licensee_country,
	REG711_LICENSEE.id,
	REG711_LICENSEE.designation,

    )
    .join(
        REG711_LICENSEE,
       REG711_LICENSEE.id==REG712_LICENSEE_STATES.id,
    )
    .order_by(
        REG712_LICENSEE_STATES.id
    )
    .distinct()  #Add " distinct" to remove duplicate
    .limit(10000)
)
     
#Show the results as a dataframe
Des_df= patstat.df(Des)
Des_df

,id,bulletin_year,bulletin_nr,licensee_seq_nr,licensee_country,id,designation
0,9770708,0,0,03,FR,9770708,as-indicated
1,9770708,0,0,03,IT,9770708,as-indicated
2,9770708,0,0,03,LT,9770708,as-indicated
3,9770708,0,0,03,DK,9770708,as-indicated
4,9770708,0,0,03,PT,9770708,as-indicated
...,...,...,...,...,...,...,...
735,23170155,0,0,02,FI,23170155,as-indicated
736,23170155,0,0,02,LV,23170155,as-indicated
737,23170155,0,0,02,SI,23170155,as-indicated
738,23170155,0,0,02,EE,23170155,as-indicated
739,23170155,0,0,02,FR,23170155,as-indicated